const General = {
    HOME:"Home",
    ABOUT:"About",
    LOGOUT:"Log Out",
    USERNAME:"Username",
    PASSWORD:"Password",
    EMAIL:"Email",
    LOGIN:"Log In",
    TITLE_LOGIN: "Computer Store",
    SIGNUP:"Sign Up",
    SUBMIT:"Submit",
    DASHBOARD:"Dashboard",
    PROFILE:"Profile",
    CART:"Cart",
    SEARCH:"Search",
    EMPTY_SEARCH:"Empty search for '{searchInput}'.",
    PRODUCT_DESCRIPTION: "Description",
    PRODUCT_LOREM_IPSUM: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    PRODUCT_ADD_CART: "Add To Cart",
    DELETE: "Delete",
    CART_TOTAL_ITEM:"Total Item(s)",
    CART_TOTAL_PRICE:"Total Price",
    LOGIN_AS_GUEST:"Log In As Guest (demo)",
    UPDATE:"Update",
    PROFILE_WAIT_MESSAGE: "Please wait, your request already in process.",
    CLOSE:"Close",
    DELETE_ACCOUNT_CONFIRMATION_TITLE:"Delete Confirmation",
    DELETE_ACCOUNT_CONFIRMATION_TEXT:"Are you sure delete this account {username}?",
    DELETE_ACCOUNT_YES_BTN:"Yes, delete this account",
    PROFILE_DEMO_DISABLE_MESSAGE: "User demo can not update/delete account.",
    PROFILE_DELETE_WAIT: "Please wait while we are deleting your data",
    CART_CHECKOUT:"Check Out",

    //payment
    PAYMENT_BTN_BACK_TO_CART:"Back To Cart",
    PAYMENT_BTN_PAY:"Pay(demo)",
    PAYMENT_DEMO_PAY_DESC:"For now, user can directly pay without input anything.",
    PAYMENT_LOADING: "Please wait, your payment already in process."
  };
  
  export default General